# Generated by Django 3.2.9 on 2022-03-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_sms_speak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='speak',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='speak',
            old_name='speak',
            new_name='name',
        ),
    ]
