# Generated by Django 3.2.9 on 2022-03-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_auto_20220327_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
