# Generated by Django 3.2.9 on 2022-04-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='photo.jpg', null=True, upload_to='media'),
        ),
    ]
